const KEY="dahlman_dashboard_v1";
const EX=["Bench Press","Incline Dumbbell Press","Tricep Cable Pushdown","Overhead Extension Bumper","Pullups","Bicep Cable Curl","Bicep Barbell Curl","Bicep Dumbbell Curl","Lateral Raise"];
const defaults={daily:[{id:crypto.randomUUID(),title:"Drink enough water"},{id:crypto.randomUUID(),title:"10 minutes of cleaning"},{id:crypto.randomUUID(),title:"Review today's tasks"}],dailyDone:{},tasks:[],workouts:[],dates:[],notes:[],snusStart:"2026-07-05"};
let data=migrate(load()),filter="all",cloudSaveTimer=null,cloudReady=false;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch{return structuredClone(defaults)}}
function migrate(x){const d={...structuredClone(defaults),...x};if(!/^\d{4}-\d{2}-\d{2}$/.test(d.snusStart||""))d.snusStart="2026-07-05";d.daily||=[];d.dailyDone||={};d.tasks||=[];d.workouts=(d.workouts||[]).map(w=>({...w,exercises:Array.isArray(w.exercises)?w.exercises:[]}));d.dates=(d.dates||[]).map(v=>({...v,reminderEnabled:v.reminderEnabled??(v.type==="Birthday"),reminderDays:Number(v.reminderDays??(v.type==="Birthday"?7:0))}));d.notes||=[];return d}
function save(msg){localStorage.setItem(KEY,JSON.stringify(data));render();queueCloudSave();if(msg)toast(msg)}
function cloudToken(){return sessionStorage.getItem("dahlman_cloud_token")||localStorage.getItem("dahlman_cloud_token")||""}
function setCloudStatus(text,state=""){const el=document.getElementById("cloudStatus");if(!el)return;el.textContent=text;el.className=`cloud-status ${state}`.trim()}
async function cloudRequest(method="GET",body){const token=cloudToken();if(!token)throw new Error("NO_TOKEN");const r=await fetch("/api/state",{method,headers:{"Authorization":`Bearer ${token}`,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});if(r.status===401)throw new Error("UNAUTHORIZED");if(r.status===404)return null;if(!r.ok)throw new Error(`HTTP_${r.status}`);return r.json()}
function queueCloudSave(){if(!cloudReady||!cloudToken())return;clearTimeout(cloudSaveTimer);setCloudStatus("Saving…","syncing");cloudSaveTimer=setTimeout(async()=>{try{await cloudRequest("PUT",{data,updatedAt:new Date().toISOString()});setCloudStatus("Synced","online")}catch(e){console.error(e);setCloudStatus("Sync failed","error")}},500)}
async function connectCloud(){let token=cloudToken();if(!token){token=prompt("Enter your private dashboard sync key:");if(!token)return;localStorage.setItem("dahlman_cloud_token",token.trim())}setCloudStatus("Connecting…","syncing");try{const remote=await cloudRequest();if(remote?.data){data=migrate(remote.data);localStorage.setItem(KEY,JSON.stringify(data));render();toast("Cloud data loaded")}else{await cloudRequest("PUT",{data,updatedAt:new Date().toISOString()});toast("Local data uploaded to cloud")}cloudReady=true;setCloudStatus("Synced","online")}catch(e){console.error(e);if(e.message==="UNAUTHORIZED"){localStorage.removeItem("dahlman_cloud_token");alert("Wrong sync key. Press Connect cloud sync and try again.")}else alert("Could not connect to cloud sync.");setCloudStatus("Local only","error")}}
async function initCloud(){if(!cloudToken()){setCloudStatus("Local only");return}await connectCloud()}
const day=()=>new Date().toISOString().slice(0,10), esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])), fmt=(s,o={day:"numeric",month:"long",year:"numeric"})=>s?new Date(s+"T12:00:00").toLocaleDateString("en-GB",o):"", diff=d=>Math.ceil((d-new Date(new Date().toDateString()))/86400000);
function nextBirthday(s){const a=new Date(s+"T12:00:00"),n=new Date(),d=new Date(n.getFullYear(),a.getMonth(),a.getDate(),12);if(d<new Date(n.getFullYear(),n.getMonth(),n.getDate(),12))d.setFullYear(d.getFullYear()+1);return d}
function nav(p){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===p));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));title.textContent=p==="dashboard"?"Welcome Mr. Dahlman":({training:"Training",tasks:"Tasks",dates:"Important dates",notes:"Notes"}[p]);if(p==="training")setTimeout(drawChart,40);scrollTo({top:0,behavior:"smooth"})}
function renderDaily(){const k=day();data.dailyDone[k]||=[];const done=data.dailyDone[k],n=done.filter(id=>data.daily.some(x=>x.id===id)).length;dailyList.innerHTML=data.daily.length?data.daily.map(x=>`<label class="check ${done.includes(x.id)?"done":""}"><input type="checkbox" data-daily="${x.id}" ${done.includes(x.id)?"checked":""}><span>${esc(x.title)}</span><i class="spacer"></i><button type="button" class="delete" data-del-daily="${x.id}">×</button></label>`).join(""):`<p class="empty">Add habits you want to repeat every day.</p>`;dailyProgress.style.width=(data.daily.length?n/data.daily.length*100:0)+"%";dailyCount.textContent=`${n}/${data.daily.length}`}
function renderTasks(){const ord={high:0,medium:1,low:2},arr=[...data.tasks].sort((a,b)=>Number(a.done)-Number(b.done)||ord[a.priority]-ord[b.priority]||(a.dueDate||"9999").localeCompare(b.dueDate||"9999")),show=arr.filter(x=>filter==="all"||(filter==="done"?x.done:!x.done));taskList.innerHTML=show.length?show.map(x=>`<article class="task ${x.done?"done":""}"><input type="checkbox" data-task="${x.id}" ${x.done?"checked":""}><div class="task-main"><h3>${esc(x.title)}</h3><p>${x.category?esc(x.category)+" · ":""}${x.dueDate?"Due "+fmt(x.dueDate,{day:"numeric",month:"short"}):"No due date"}${x.notes?" · "+esc(x.notes):""}</p></div><div><span class="tag ${x.priority}">${{high:"High",medium:"Normal",low:"Low"}[x.priority]}</span><button class="delete" data-del-task="${x.id}">×</button></div></article>`).join(""):`<p class="empty">Nothing here. Either impressive or suspicious.</p>`;const open=arr.filter(x=>!x.done);openCount.textContent=open.length;priority.innerHTML=open.length?open.slice(0,4).map(x=>`<div class="compact ${x.priority}"><i></i><div><b>${esc(x.title)}</b><span>${x.dueDate?fmt(x.dueDate,{day:"numeric",month:"short"}):"No due date"}</span></div></div>`).join(""):`<p class="empty">Everything is done. Solid.</p>`}
function metrics(e){const s=(e.sets||[]).filter(x=>+x.weight>0&&+x.reps>0);return{bestWeight:s.length?Math.max(...s.map(x=>+x.weight)):0,estimated1RM:s.length?Math.max(...s.map(x=>+x.weight*(1+(+x.reps)/30))):0,volume:s.reduce((a,x)=>a+(+x.weight)*(+x.reps),0)}}
function renderWorkouts(){const arr=[...data.workouts].sort((a,b)=>b.date.localeCompare(a.date)),m=day().slice(0,7);totalWorkouts.textContent=arr.length;monthWorkouts.textContent=monthCount.textContent=arr.filter(x=>x.date.startsWith(m)).length;const bw=arr.find(x=>x.bodyweight);latestWeight.textContent=bw?`${bw.bodyweight} kg`:"–";workoutList.innerHTML=arr.length?arr.map(w=>`<article class="workout"><div class="workout-top"><div><div class="workout-date">${fmt(w.date,{day:"numeric",month:"short",year:"numeric"})}</div><h3>${esc(w.title)}</h3><p>${w.duration?esc(w.duration)+" min":""}${w.duration&&w.bodyweight?" · ":""}${w.bodyweight?esc(w.bodyweight)+" kg bodyweight":""}</p></div><button class="delete" data-del-workout="${w.id}">×</button></div>${(w.exercises||[]).map(e=>`<div class="exercise-item"><b>${esc(e.name)}</b><span>${e.sets.map((s,i)=>`Set ${i+1}: ${s.weight} kg × ${s.reps}`).join(" · ")}</span></div>`).join("")}${w.notes?`<p><em>${esc(w.notes)}</em></p>`:""}</article>`).join(""):`<p class="empty">Log your first workout to start building history.</p>`;latestWorkout.innerHTML=arr.length?dateBox(arr[0].title,new Date(arr[0].date+"T12:00:00"),`${arr[0].exercises?.length||0} exercises${arr[0].bodyweight?" · "+arr[0].bodyweight+" kg":""}`):`<p class="empty">No workouts logged yet.</p>`;chartExercise.innerHTML=EX.map(x=>`<option>${x}</option>`).join("");drawChart()}
function dateBox(name,d,sub){return`<div class="datebox"><div class="badge"><b>${d.getDate()}</b><span>${d.toLocaleDateString("en-GB",{month:"short"})}</span></div><div><h3>${esc(name)}</h3><p>${sub}</p></div></div>`}
function renderDates(){const arr=[...data.dates].sort((a,b)=>a.date.localeCompare(b.date));dateList.innerHTML=arr.length?arr.map(x=>{const b=x.type==="Birthday",d=b?nextBirthday(x.date):new Date(x.date+"T12:00:00"),n=diff(d),rel=n===0?"Today":n===1?"Tomorrow":n>1?`${n} days remaining`:`${-n} days ago`;return`<article class="date-card"><button class="delete" data-del-date="${x.id}">×</button><div class="date-line">${fmt(x.date)} · ${rel}</div><h3>${esc(x.title)}</h3><p>${esc(x.type)}${x.notes?"\n"+esc(x.notes):""}</p>${x.reminderEnabled?`<span class="chip">Reminder ${x.reminderDays} day${+x.reminderDays===1?"":"s"} before</span>`:""}</article>`}).join(""):`<p class="empty">Add birthdays, deadlines, trips and other dates.</p>`;const future=arr.filter(x=>x.type!=="Birthday"&&diff(new Date(x.date+"T12:00:00"))>=0)[0];nextDate.innerHTML=future?dateBox(future.title,new Date(future.date+"T12:00:00"),`${diff(new Date(future.date+"T12:00:00"))} days remaining`):`<p class="empty">No upcoming dates.</p>`;const bs=arr.filter(x=>x.type==="Birthday").map(x=>({x,d:nextBirthday(x.date)})).sort((a,b)=>a.d-b.d);birthday.innerHTML=bs.length?dateBox(bs[0].x.title,bs[0].d,`${diff(bs[0].d)} days remaining`):`<p class="empty">No birthdays added yet.</p>`;renderReminders()}
function due(){return data.dates.filter(x=>x.reminderEnabled).map(x=>({x,d:x.type==="Birthday"?nextBirthday(x.date):new Date(x.date+"T12:00:00")})).map(v=>({...v,n:diff(v.d)})).filter(v=>v.n>=0&&v.n<=+v.x.reminderDays)}
function renderReminders(){const a=due();reminders.classList.toggle("hide",!a.length);reminders.innerHTML=a.length?`<b>Reminder:</b> ${a.map(v=>`${esc(v.x.title)} ${v.n===0?"is today":v.n===1?"is tomorrow":`is in ${v.n} days`}`).join(" · ")}`:""}
function renderNotes(){const a=[...data.notes].sort((x,y)=>y.created.localeCompare(x.created));noteList.innerHTML=a.length?a.map(x=>`<article class="note-card"><button class="delete" data-del-note="${x.id}">×</button><small>${fmt(x.created.slice(0,10),{day:"numeric",month:"short"})}</small><h3>${esc(x.title)}</h3><p>${esc(x.content)}</p></article>`).join(""):`<p class="empty">No notes yet.</p>`}
function renderSnus(){const n=Math.max(0,Math.floor((new Date(new Date().toDateString())-new Date(data.snusStart+"T12:00:00"))/86400000));snusDays.textContent=n;snusSince.textContent=`Since ${fmt(data.snusStart)}`}
function render(){today.textContent=new Date().toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"});renderSnus();renderDaily();renderTasks();renderWorkouts();renderDates();renderNotes();notify()}
function openModal(id){document.querySelectorAll("dialog[open]").forEach(x=>x.close());const d=document.getElementById(id);if(id==="workoutModal"){d.querySelector('[name="date"]').value=day();exerciseRows.innerHTML="";addExerciseRow()}d.showModal()}
function options(){return EX.map(x=>`<option>${x}</option>`).join("")}
function addExerciseRow(){const r=document.createElement("div");r.className="exercise-row";r.innerHTML=`<div class="exercise-row-head"><select class="exercise-name">${options()}</select><button type="button" class="delete remove-ex">×</button></div><div class="sets"></div><button type="button" class="add-set">+ Add set</button>`;exerciseRows.appendChild(r);for(let i=0;i<3;i++)addSet(r.querySelector(".sets"))}
function addSet(list){const r=document.createElement("div");r.className="set-row";r.innerHTML=`<span>Set ${list.children.length+1}</span><label>Weight (kg)<input class="weight" type="number" min="0" step=".5" value="0"></label><label>Reps<input class="reps" type="number" min="0" value="0"></label><button type="button" class="delete remove-set">×</button>`;list.appendChild(r)}
function drawChart(){const c=document.getElementById("chart");if(!c)return;const ctx=c.getContext("2d"),ex=chartExercise.value,met=chartMetric.value,p=data.workouts.flatMap(w=>(w.exercises||[]).filter(e=>e.name===ex).map(e=>({date:w.date,value:metrics(e)[met]}))).filter(x=>x.value>0).sort((a,b)=>a.date.localeCompare(b.date)),r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=Math.max(600,r.width*dpr);c.height=350*dpr;ctx.scale(dpr,dpr);const W=c.width/dpr,H=350;ctx.clearRect(0,0,W,H);chartEmpty.style.display=p.length<2?"block":"none";if(p.length<2)return;const pad={l:55,r:18,t:25,b:42},mn=Math.min(...p.map(x=>x.value)),mx=Math.max(...p.map(x=>x.value)),rg=Math.max(1,mx-mn),lo=Math.max(0,mn-rg*.15),hi=mx+rg*.15;ctx.font="12px system-ui";for(let i=0;i<5;i++){const y=pad.t+(H-pad.t-pad.b)*i/4;ctx.strokeStyle="#ffffff17";ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(W-pad.r,y);ctx.stroke();ctx.fillStyle="#a4a4ab";ctx.fillText((hi-(hi-lo)*i/4).toFixed(met==="volume"?0:1),5,y+4)}const X=i=>pad.l+(W-pad.l-pad.r)*i/(p.length-1),Y=v=>pad.t+(H-pad.t-pad.b)*(hi-v)/(hi-lo);ctx.strokeStyle="#e3262e";ctx.lineWidth=3;ctx.beginPath();p.forEach((q,i)=>i?ctx.lineTo(X(i),Y(q.value)):ctx.moveTo(X(i),Y(q.value)));ctx.stroke();p.forEach((q,i)=>{ctx.fillStyle="#ff4b52";ctx.beginPath();ctx.arc(X(i),Y(q.value),5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#aaa";ctx.fillText(fmt(q.date,{day:"numeric",month:"short"}),Math.max(0,X(i)-24),H-15)})}
function toast(s){const t=document.getElementById("toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1700)}
async function notify(){if(!("Notification"in window)||Notification.permission!=="granted")return;const k="dahlman_notification_"+day();if(localStorage.getItem(k)||!due().length)return;new Notification("Dahlman Dashboard",{body:due().map(v=>`${v.x.title}: ${v.n===0?"today":v.n+" day(s) remaining"}`).join("\n")});localStorage.setItem(k,"1")}
document.addEventListener("click",e=>{const n=e.target.closest("[data-page]");if(n)nav(n.dataset.page);const g=e.target.closest("[data-go]");if(g)nav(g.dataset.go);const m=e.target.closest("[data-modal]");if(m){e.preventDefault();openModal(m.dataset.modal)}if(e.target.matches("[data-close]"))e.target.closest("dialog").close();if(e.target.closest(".add-set"))addSet(e.target.closest(".exercise-row").querySelector(".sets"));if(e.target.closest(".remove-set")){const l=e.target.closest(".sets");e.target.closest(".set-row").remove();[...l.children].forEach((x,i)=>x.firstElementChild.textContent=`Set ${i+1}`)}if(e.target.closest(".remove-ex"))e.target.closest(".exercise-row").remove();for(const[k,a]of[["daily","daily"],["task","tasks"],["workout","workouts"],["date","dates"],["note","notes"]]){const el=e.target.closest(`[data-del-${k}]`);if(el&&confirm("Delete this item?")){data[a]=data[a].filter(x=>x.id!==el.dataset["del"+k[0].toUpperCase()+k.slice(1)]);save("Deleted")}}});
document.addEventListener("change",e=>{if(e.target.matches("[data-daily]")){const k=day(),id=e.target.dataset.daily;data.dailyDone[k]||=[];data.dailyDone[k]=e.target.checked?[...new Set([...data.dailyDone[k],id])]:data.dailyDone[k].filter(x=>x!==id);save()}if(e.target.matches("[data-task]")){const x=data.tasks.find(v=>v.id===e.target.dataset.task);if(x){x.done=e.target.checked;save()}}});
document.querySelectorAll(".filter").forEach(x=>x.onclick=()=>{filter=x.dataset.filter;document.querySelectorAll(".filter").forEach(y=>y.classList.toggle("active",y===x));renderTasks()});
const fd=f=>Object.fromEntries(new FormData(f).entries());
dailyForm.onsubmit=e=>{e.preventDefault();const v=fd(e.target);data.daily.push({id:crypto.randomUUID(),title:v.title});e.target.reset();e.target.closest("dialog").close();save("Habit added")};
taskForm.onsubmit=e=>{e.preventDefault();data.tasks.push({id:crypto.randomUUID(),...fd(e.target),done:false,created:new Date().toISOString()});e.target.reset();e.target.closest("dialog").close();save("Task added")};
workoutForm.onsubmit=e=>{e.preventDefault();const v=fd(e.target),exercises=[...document.querySelectorAll(".exercise-row")].map(r=>({name:r.querySelector(".exercise-name").value,sets:[...r.querySelectorAll(".set-row")].map(s=>({weight:+s.querySelector(".weight").value||0,reps:+s.querySelector(".reps").value||0})).filter(s=>s.reps>0)})).filter(x=>x.sets.length);data.workouts.push({id:crypto.randomUUID(),...v,exercises,created:new Date().toISOString()});e.target.reset();e.target.closest("dialog").close();save("Workout saved")};
dateForm.onsubmit=e=>{e.preventDefault();const v=fd(e.target);data.dates.push({id:crypto.randomUUID(),...v,reminderEnabled:e.target.reminderEnabled.checked,reminderDays:+v.reminderDays});e.target.reset();e.target.reminderEnabled.checked=true;e.target.reminderDays.value="7";e.target.closest("dialog").close();save("Date added")};
noteForm.onsubmit=e=>{e.preventDefault();data.notes.push({id:crypto.randomUUID(),...fd(e.target),created:new Date().toISOString()});e.target.reset();e.target.closest("dialog").close();save("Note saved")};
quick.onclick=()=>openModal("quickModal");addExercise.onclick=addExerciseRow;chartExercise.onchange=drawChart;chartMetric.onchange=drawChart;window.onresize=()=>setTimeout(drawChart,60);
resetSnus.onclick=()=>{if(confirm("Reset the snus counter to today?")){data.snusStart=day();save("Snus counter reset")}};
notifyBtn.onclick=async()=>{if(!("Notification"in window)){alert("This browser does not support notifications.");return}const p=await Notification.requestPermission();toast(p==="granted"?"Notifications enabled":"Notifications not enabled");notify()};
document.getElementById("export").onclick=()=>{const b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`dahlman-dashboard-backup-${day()}.json`;a.click();URL.revokeObjectURL(a.href)};
document.getElementById("import").onchange=async e=>{try{data=migrate(JSON.parse(await e.target.files[0].text()));save("Backup imported")}catch{alert("Could not read backup.")}e.target.value=""};
document.getElementById("cloudSetup").onclick=connectCloud;
window.addEventListener("online",()=>{if(cloudToken())connectCloud()});
render();initCloud();