(()=>{
'use strict';
if(document.getElementById('casino')) return;
const TASKS=['Tømme sorte søppel traller','Tømme plast stativ','Tømme restavfall containere','Tømme rent treverk containere','Tømme impregnert containere','Rydde sticks og søppel ute','Rydde trelast hyller inne','Rydde trelast hyller ute','Varepåfyll trelast inne','Varepåfyll gips','Varepåfyll treplater','Varepåfyll isolasjon og XPS','Varepåfyll trelast ute','Varepåfyll betong','Rydde betong skuret','Rydde ASAK','Rydde Glava og Rockwool','Rydde listverk rommet','Ta av plast listverk','Ta av plast beslag','Rydde takrenne boden','Rydde sagrommet','Tømme støvsuger sagrommet','Rydde PC og skranken'];
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const style=document.createElement('style');style.id='bm-casino-styles';style.textContent=`
.casino-shell{display:grid;gap:16px}.casino-stage{padding:22px;border:1px solid var(--line);border-radius:24px;background:linear-gradient(145deg,rgba(31,11,14,.92),rgba(12,12,14,.94));box-shadow:0 20px 60px rgba(0,0,0,.32)}.casino-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.casino-title h3{font-size:34px;letter-spacing:-.04em}.casino-title p{color:var(--muted);margin:5px 0 0}.casino-reels{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:22px 0}.casino-reel{min-height:120px;display:grid;place-items:center;text-align:center;padding:12px;border-radius:16px;border:1px solid rgba(255,255,255,.12);background:linear-gradient(180deg,#3a2517,#18100b);box-shadow:inset 0 0 0 3px rgba(255,255,255,.025);font-weight:900}.casino-reel.spinning{animation:casinoReelPulse .22s linear infinite alternate}@keyframes casinoReelPulse{to{transform:translateY(-4px);filter:brightness(1.35)}}.casino-results{display:grid;gap:8px}.casino-result{display:flex;justify-content:space-between;gap:12px;padding:12px 14px;border-radius:12px;background:#f1ead8;color:#201a13}.casino-result.asap{border:2px solid #e3262e;color:#9d1117;font-weight:950}.casino-actions{display:flex;gap:8px;flex-wrap:wrap}.casino-task-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:12px}.casino-task-list.hide{display:none}.casino-task-list label{display:flex;gap:8px;align-items:center;padding:10px;background:#ffffff07;border-radius:10px}.casino-task-list input{width:auto}@media(max-width:900px){.casino-task-list{grid-template-columns:1fr}}@media(max-width:700px){aside nav{display:flex!important;grid-template-columns:none!important;overflow-x:auto!important;overflow-y:hidden!important;gap:5px!important;scrollbar-width:none;-webkit-overflow-scrolling:touch;overscroll-behavior-x:contain}aside nav::-webkit-scrollbar{display:none}.nav{flex:0 0 74px!important;min-width:74px!important}.nav span{display:block!important;font-size:9px!important;margin-top:3px}.casino-reels{grid-template-columns:1fr 1fr}.casino-reel{min-height:95px}.casino-head{align-items:flex-start}.casino-title h3{font-size:28px}}
`;document.head.appendChild(style);
const nav=document.querySelector('aside nav');
if(nav&&!nav.querySelector('[data-page="casino"]')){const training=nav.querySelector('[data-page="training"]');const btn=document.createElement('button');btn.className='nav';btn.dataset.page='casino';btn.innerHTML='♠ <span>BM Casino</span>';training?.nextSibling?nav.insertBefore(btn,training.nextSibling):nav.appendChild(btn)}
const notesPage=document.getElementById('notes');
const page=document.createElement('section');page.id='casino';page.className='page content';page.innerHTML=`<div class="toolbar"><div><small>BYGGMAKKER SKUI</small><h2>BM Casino</h2></div></div><div class="casino-shell"><div class="casino-stage"><div class="casino-head"><div class="casino-title"><small>TRELAST</small><h3>Dagens trekning</h3><p>Fire oppgaver. Duplikater blir merket ASAP.</p></div><button id="casinoSpin" class="primary" type="button">SPINN</button></div><div id="casinoReels" class="casino-reels">${[0,1,2,3].map(()=>'<div class="casino-reel">Klar</div>').join('')}</div><div class="casino-actions"><button id="casinoClear" class="outline" type="button">Tøm resultat</button><button id="casinoToggleTasks" class="outline" type="button">Rediger oppgavepool</button></div><div id="casinoTaskPool" class="casino-task-list hide">${TASKS.map((t,i)=>`<label><input type="checkbox" data-casino-task="${i}" checked><span>${escapeHtml(t)}</span></label>`).join('')}</div></div><div class="card"><div class="head"><div><small>RESULTAT</small><h3>Arbeidsliste</h3></div></div><div id="casinoResults" class="casino-results"><p class="empty">Ingen trekning ennå.</p></div></div></div>`;
notesPage?notesPage.parentNode.insertBefore(page,notesPage):document.querySelector('main')?.appendChild(page);
function selectedPool(){return [...document.querySelectorAll('[data-casino-task]:checked')].map(x=>TASKS[Number(x.dataset.casinoTask)])}
function spin(){const pool=selectedPool();if(!pool.length){document.getElementById('casinoResults').innerHTML='<p class="empty">Velg minst én oppgave.</p>';return}const reels=[...document.querySelectorAll('.casino-reel')];reels.forEach(r=>r.classList.add('spinning'));let ticks=0;const timer=setInterval(()=>{reels.forEach(r=>r.textContent=pool[Math.floor(Math.random()*pool.length)]);if(++ticks>12){clearInterval(timer);reels.forEach(r=>r.classList.remove('spinning'));const picks=reels.map(r=>r.textContent),counts={};picks.forEach(x=>counts[x]=(counts[x]||0)+1);document.getElementById('casinoResults').innerHTML=picks.map((x,i)=>`<div class="casino-result ${counts[x]>1?'asap':''}"><span>${i+1}. ${escapeHtml(x)}</span><b>${counts[x]>1?'ASAP':''}</b></div>`).join('')}},90)}
document.addEventListener('click',e=>{if(e.target.id==='casinoSpin')spin();if(e.target.id==='casinoClear')document.getElementById('casinoResults').innerHTML='<p class="empty">Ingen trekning ennå.</p>';if(e.target.id==='casinoToggleTasks')document.getElementById('casinoTaskPool').classList.toggle('hide')});
})();
