(()=>{
const V6_IMAGES=Array.from({length:9},(_,i)=>`assets/background-${String(i+1).padStart(2,'0')}.jpg`);
const CASINO_TASKS=['Tømme sorte søppel traller','Tømme plast stativ','Tømme restavfall containere','Tømme rent treverk containere','Tømme impregnert containere','Rydde sticks og søppel ute','Rydde trelast hyller inne','Rydde trelast hyller ute','Varepåfyll trelast inne','Varepåfyll gips','Varepåfyll treplater','Varepåfyll isolasjon og XPS','Varepåfyll trelast ute','Varepåfyll betong','Rydde betong skuret','Rydde ASAK','Rydde Glava og Rockwool','Rydde listverk rommet','Ta av plast listverk','Ta av plast beslag','Rydde takrenne boden','Rydde sagrommet','Tømme støvsuger sagrommet','Rydde PC og skranken'];
function ensureDaily(){if(!data.daily.some(x=>x.title==='Wash Face'))data.daily.push({id:'daily-wash-face',title:'Wash Face'})}
ensureDaily();
// Branding
const brand=document.querySelector('.brand');if(brand){brand.querySelector('b').textContent='';const small=brand.querySelector('small');if(small)small.textContent='Dashboard'}
// Add BM Casino navigation/page
const notesNav=document.querySelector('.nav[data-page="notes"]');if(notesNav&&!document.querySelector('.nav[data-page="casino"]'))notesNav.insertAdjacentHTML('beforebegin','<button class="nav" data-page="casino">♠ <span>BM Casino</span></button>');
const notesPage=document.getElementById('notes');if(notesPage&&!document.getElementById('casino'))notesPage.insertAdjacentHTML('beforebegin',`<section id="casino" class="page content"><div class="toolbar"><div><small>BYGGMAKKER SKUI</small><h2>BM Casino</h2></div></div><div class="casino-shell"><div class="casino-stage"><div class="casino-head"><div class="casino-title"><small>TRELAST</small><h3>Today’s draw</h3><p>Four jobs. Duplicates become ASAP.</p></div><button id="casinoSpin" class="primary">SPIN</button></div><div id="casinoReels" class="casino-reels">${[0,1,2,3].map(()=>'<div class="casino-reel">Ready</div>').join('')}</div><div class="casino-actions"><button id="casinoClear" class="outline">Clear results</button><button id="casinoToggleTasks" class="outline">Edit task pool</button></div><div id="casinoTaskPool" class="casino-task-list hide">${CASINO_TASKS.map((t,i)=>`<label><input type="checkbox" data-casino-task="${i}" checked><span>${esc(t)}</span></label>`).join('')}</div></div><div class="card"><div class="head"><div><small>RESULTS</small><h3>Work list</h3></div></div><div id="casinoResults" class="casino-results"><p class="empty">No draw yet.</p></div></div></div></section>`);
// Home rearrangement
const dashboard=document.getElementById('dashboard'),hero=dashboard?.querySelector('.hero'),world=dashboard?.querySelector('.world-widget');
if(dashboard&&hero&&!dashboard.querySelector('.home-top-grid')){const grid=document.createElement('div');grid.className='home-top-grid';hero.parentNode.insertBefore(grid,hero);grid.appendChild(hero);const photo=document.createElement('div');photo.className='photo-widget';photo.innerHTML=V6_IMAGES.map((src,i)=>`<img src="${src}" class="${i===0?'active':''}" alt="">`).join('')+'<div class="photo-label">OUR MOMENTS</div>';grid.appendChild(photo);let idx=0;setInterval(()=>{const imgs=photo.querySelectorAll('img');imgs[idx].classList.remove('active');idx=(idx+1)%imgs.length;imgs[idx].classList.add('active')},16000)}
if(hero){const h2=hero.querySelector('h2'),headerTitle=document.getElementById('title');if(h2&&headerTitle){const welcome=headerTitle.textContent;headerTitle.textContent=h2.textContent;h2.textContent=welcome}}
if(world&&!world.querySelector('.today-panel')){const wrap=document.createElement('div');wrap.className='date-weather-widget';world.parentNode.insertBefore(wrap,world);const todayPanel=document.createElement('div');todayPanel.className='today-panel';todayPanel.innerHTML='<small>TODAY</small><b id="todayDay"></b><span id="todayFull"></span>';wrap.append(todayPanel,world);function updateToday(){const n=new Date();document.getElementById('todayDay').textContent=n.toLocaleDateString('en-GB',{weekday:'long'});document.getElementById('todayFull').textContent=n.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}updateToday();document.getElementById('today').style.display='none'}
function setPageState(p){document.body.classList.toggle('home-page',p==='dashboard')}
document.addEventListener('click',e=>{const n=e.target.closest('[data-page],[data-go]');if(n)setTimeout(()=>setPageState(n.dataset.page||n.dataset.go),0)});setPageState('dashboard');
// Shopping button after items
const oldRenderShopping=renderShopping;renderShopping=function(){oldRenderShopping();document.querySelectorAll('.shopping-card').forEach(card=>{const add=card.querySelector('[data-add-shopping]');if(!add)return;const target=card.querySelector('.shopping-items');const btn=document.createElement('button');btn.className='outline add-item-inline';btn.dataset.addShopping=add.dataset.addShopping;btn.textContent='+ Add item';target.appendChild(btn)})};
// Birthday layout
const oldRenderDatesV6=renderDates;renderDates=function(){oldRenderDatesV6();document.querySelectorAll('#dateList .date-card').forEach((card,i)=>{const entry=[...data.dates.map(x=>({...x,kind:'date'})),...data.countdowns.map(x=>({...x,kind:'countdown'})),...(data.daysSince||[]).map(x=>({...x,kind:'daysSince'}))].sort((a,b)=>a.date.localeCompare(b.date))[i];if(!entry||entry.type!=='Birthday')return;const born=new Date(entry.date+'T12:00:00'),now=new Date(),next=new Date(now.getFullYear(),born.getMonth(),born.getDate(),12);if(next<new Date(now.getFullYear(),now.getMonth(),now.getDate(),12))next.setFullYear(next.getFullYear()+1);const until=Math.ceil((next-new Date(new Date().toDateString()))/86400000),lived=Math.max(0,Math.floor((new Date()-born)/86400000));card.querySelector('.date-line').textContent='Birthday';const p=card.querySelector('p');if(p)p.outerHTML=`<div class="birthday-layout"><p>Born <b>${born.toLocaleDateString('en-GB',{month:'long',day:'numeric',year:'numeric'})}</b></p><p>Next birthday in <b>${until} days</b></p><p>Days lived <b>${lived.toLocaleString('en-GB')}</b></p></div>`})};
// Budget: expenses first
const oldRenderBudgetV6=renderBudget;renderBudget=function(){oldRenderBudgetV6();const sheet=document.querySelector('.budget-excel-grid,.budget-sheet-grid');if(sheet&&sheet.children.length>1)sheet.insertBefore(sheet.children[1],sheet.children[0]);const stats=document.querySelector('#budget .stats');if(stats&&stats.children.length>=2)stats.insertBefore(stats.children[1],stats.children[0])};
// Casino actions
function casinoPool(){return [...document.querySelectorAll('[data-casino-task]:checked')].map(x=>CASINO_TASKS[+x.dataset.casinoTask])}
function spinCasino(){const pool=casinoPool();if(!pool.length)return;const reels=[...document.querySelectorAll('.casino-reel')];reels.forEach(x=>x.classList.add('spinning'));let ticks=0;const timer=setInterval(()=>{reels.forEach(r=>r.textContent=pool[Math.floor(Math.random()*pool.length)]);if(++ticks>12){clearInterval(timer);reels.forEach(x=>x.classList.remove('spinning'));const picks=reels.map(r=>r.textContent),counts={};picks.forEach(x=>counts[x]=(counts[x]||0)+1);document.getElementById('casinoResults').innerHTML=picks.map((x,i)=>`<div class="casino-result ${counts[x]>1?'asap':''}"><span>${i+1}. ${esc(x)}</span><b>${counts[x]>1?'ASAP':''}</b></div>`).join('')}} ,90)}
document.addEventListener('click',e=>{if(e.target.id==='casinoSpin')spinCasino();if(e.target.id==='casinoClear')document.getElementById('casinoResults').innerHTML='<p class="empty">No draw yet.</p>';if(e.target.id==='casinoToggleTasks')document.getElementById('casinoTaskPool').classList.toggle('hide')});
// Extend nav titles without duplicates
const oldNavV6=nav;nav=function(p){oldNavV6(p);setPageState(p);if(p==='casino')document.getElementById('title').textContent='BM Casino'};
render();
})();